site_name: Fedago
site_url: https://fedago.example.com
site_description: Federated Data Governance for AI Tools

nav:
  - Home: index.md
  - About: about.md
  - Project Plan and Roadmap:
    - 2024 Roadmap: Roadmap/roadmap.md
    - 2024 Menus (Offerings):
      - Fall Menu: Roadmap/2024_Q2.md
      - Summer Menu: Roadmap/2024_Q3.md
      - Spring Menu: Roadmap/2024_Q4.md
  - Fedago Layer Details: layer.md
  - Investors: investors.md
  - Contact: contact.md

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.tracking  

# repo_url: https://github.com/Radovici/Fedago

extra:
  analytics:
    provider: google
    property: G-CV1PVG0585